language: php
sudo: false
php:
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - app/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
